st = 'slslslslsalslslslsllllllslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslslsalslslslsls%40dontwannacry.com'

print(len(st))
